name: tide
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  riverpod_annotation: ^2.3.5
  flutter_colorpicker: ^1.1.0
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  gap: ^3.0.1
  mockito: ^5.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  drift_dev: ^2.20.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
